import VisualDashAreaGeneral from "./VisualDashAreaGeneral";
import { IData, IDataContext, TToogleGeneral, IRecords } from "../../types";
import { createContext, useState } from "react";
import BreadCrumbs from "../../components/BreadCrumbs";
import VisualDashAreaDetails from "../../components/VisualDashAreaDetails";

const GeneralData: IData[] = [
  {
    id: 0,
    name: "Server 1",
    online: true,
    today: 11.2,
    lastSevenDay: [22.2, 11.3, 21.6, 2, 5.4, 14.7, 24],
    subModules: [
      {
        id: 0,
        name: "module 1",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 1,
        name: "module 2",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 2,
        name: "module 3",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 3,
        name: "module 4",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 4,
        name: "module 5",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 5,
        name: "module 6",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 6,
        name: "module 7",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 0,
        name: "module 1",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 1,
        name: "module 2",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 2,
        name: "module 3",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 3,
        name: "module 4",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 4,
        name: "module 5",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 5,
        name: "module 6",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 6,
        name: "module 7",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
    ],
  },
  {
    id: 1,
    name: "Server 2",
    online: false,
    today: 11.2,
    lastSevenDay: [21.2, 21.3, 11.6, 22, 1.4, 12.7, 23],
    subModules: [
      {
        id: 0,
        name: "module 1",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 1,
        name: "module 2",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 2,
        name: "module 3",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 3,
        name: "module 4",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 4,
        name: "module 5",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 5,
        name: "module 6",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 6,
        name: "module 7",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
    ],
  },
  {
    id: 2,
    name: "Server 3",
    online: false,
    today: 16.2,
    lastSevenDay: [12.2, 9.3, 21.6, 5, 5.4, 19.7, 23],
    subModules: [
      {
        id: 0,
        name: "module 1",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 1,
        name: "module 2",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 2,
        name: "module 3",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 3,
        name: "module 4",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 4,
        name: "module 5",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 5,
        name: "module 6",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 6,
        name: "module 7",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
    ],
  },
  {
    id: 3,
    name: "Server 4",
    online: false,
    today: 2.2,
    lastSevenDay: [2.2, 11.3, 21.6, 2, 5.4, 14.7, 24],
    subModules: [
      {
        id: 0,
        name: "module 1",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 1,
        name: "module 2",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 2,
        name: "module 3",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 3,
        name: "module 4",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 4,
        name: "module 5",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 5,
        name: "module 6",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 6,
        name: "module 7",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
    ],
  },
  {
    id: 4,
    name: "Server 5",
    online: true,
    today: 11.2,
    lastSevenDay: [22.2, 11.3, 21.6, 2, 5.4, 14.7, 24],
    subModules: [
      {
        id: 0,
        name: "module 1",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 1,
        name: "module 2",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 2,
        name: "module 3",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 3,
        name: "module 4",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 4,
        name: "module 5",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 5,
        name: "module 6",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 6,
        name: "module 7",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
    ],
  },
  {
    id: 5,
    name: "Server 6",
    online: true,
    today: 13.2,
    lastSevenDay: [12.2, 15.3, 16.6, 7, 2, 0, 23],
    subModules: [
      {
        id: 0,
        name: "module 1",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 1,
        name: "module 2",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 2,
        name: "module 3",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 3,
        name: "module 4",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 4,
        name: "module 5",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 5,
        name: "module 6",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 6,
        name: "module 7",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
    ],
  },
  {
    id: 6,
    name: "Server 7",
    online: false,
    today: 1.2,
    lastSevenDay: [21.2, 17.3, 19.6, 2, 3.4, 10.7, 21],
    subModules: [
      {
        id: 0,
        name: "module 1",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 1,
        name: "module 2",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 2,
        name: "module 3",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 3,
        name: "module 4",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 4,
        name: "module 5",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 5,
        name: "module 6",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 6,
        name: "module 7",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
    ],
  },
  {
    id: 7,
    name: "Server 8",
    online: true,
    today: 16,
    lastSevenDay: [22.2, 11.3, 21.6, 2, 5.4, 14.7, 24],
    subModules: [
      {
        id: 0,
        name: "module 1",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 1,
        name: "module 2",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 2,
        name: "module 3",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 3,
        name: "module 4",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 4,
        name: "module 5",
        active: false,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 5,
        name: "module 6",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
      {
        id: 6,
        name: "module 7",
        active: true,
        statusCode: "200",
        lastTimeChecked: "date",
        state: true,
        activePercentage: 50,
      },
    ],
  },
];

// const GeneralData: IRecords[] = [
//   {
//     sla_service: "string",
//     application_id: 0,
//     main_application_name: "Server 1",
//     main_application_id: 0,
//     application_name: "App Server 1",
//     result_code: 500,
//     result: "Fail",
//   },
//   {
//     sla_service: "string",
//     application_id: 1,
//     main_application_name: "Server 2",
//     main_application_id: 1,
//     application_name: "App Server 2",
//     result_code: 500,
//     result: "Fail",
//   },
//   {
//     sla_service: "string",
//     application_id: 2,
//     main_application_name: "Server 3",
//     main_application_id: 2,
//     application_name: "App Server 3",
//     result_code: 200,
//     result: "Success",
//   },
//   {
//     sla_service: "string",
//     application_id: 3,
//     main_application_name: "Server 4",
//     main_application_id: 3,
//     application_name: "App Server 4",
//     result_code: 200,
//     result: "Success",
//   },
//   {
//     sla_service: "string",
//     application_id: 4,
//     main_application_name: "Server 5",
//     main_application_id: 4,
//     application_name: "App Server 5",
//     result_code: 200,
//     result: "Success",
//   },
//   {
//     sla_service: "string",
//     application_id: 5,
//     main_application_name: "Server 6",
//     main_application_id: 5,
//     application_name: "App Server 6",
//     result_code: 200,
//     result: "Success",
//   },
//   {
//     sla_service: "string",
//     application_id: 6,
//     main_application_name: "Server 7",
//     main_application_id: 6,
//     application_name: "App Server 7",
//     result_code: 200,
//     result: "Success",
//   },
//   {
//     sla_service: "string",
//     application_id: 7,
//     main_application_name: "Server 8",
//     main_application_id: 7,
//     application_name: "App Server 8",
//     result_code: 200,
//     result: "Success",
//   },
// ];

export const GeneralDataContext = createContext<IDataContext | null>(null);

function DashBoard() {
  const [toggleGeneral, setToggleGeneral] = useState<TToogleGeneral>("General");
  const BreadCrumbsItems = GeneralData.map((GeneralDatum: IData) => ({
    title: GeneralDatum.name,
    id: GeneralDatum.id,
    onClick: () => setToggleGeneral("General"),
  }));

  return (
    <GeneralDataContext.Provider value={{ GeneralData, setToggleGeneral }}>
      {toggleGeneral !== "General" ? (
        <BreadCrumbs
          items={BreadCrumbsItems}
          currentIndex={toggleGeneral}
          setCurrentIndex={setToggleGeneral}
        />
      ) : null}
      {toggleGeneral === "General" ? (
        <VisualDashAreaGeneral />
      ) : (
        <div>
          <VisualDashAreaDetails
            data={GeneralData.filter((ele) => ele.id === toggleGeneral)[0]}
          />
        </div>
      )}
    </GeneralDataContext.Provider>
  );
}

export default DashBoard;
